# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-17 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_photo', models.CharField(blank=True, max_length=600)),
                ('key', models.CharField(max_length=300)),
                ('last_modified', models.DateTimeField()),
                ('etag', models.CharField(max_length=300)),
                ('size', models.IntegerField()),
                ('storage_class', models.CharField(max_length=100)),
                ('exif_keys', jsonfield.fields.JSONField(default={})),
            ],
        ),
    ]
