# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-16 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=300)),
                ('last_modified', models.DateTimeField()),
                ('etag', models.CharField(max_length=300)),
                ('size', models.IntegerField()),
                ('storage_class', models.CharField(max_length=100)),
            ],
        ),
    ]
